In [19]:
#NumPy

import numpy as np

a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [2]:
b= np.array([[9.0,8.0,5.8], [6.0,5.0,4.0]])
print(b)

[[9.  8.  5.8]
 [6.  5.  4. ]]


In [73]:
# Get dimension
a.ndim
b.ndim

3

In [7]:
#Get shape
a.shape


(3,)

In [6]:
b.shape

(2, 3)

In [14]:
# Get type 
a.dtype

dtype('int16')

In [22]:
b.dtype
b.itemsize

8

In [18]:
a.size
a.itemsize

2

In [21]:
# total size

a.size * a.itemsize

a.nbytes

12

In [29]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(ar)
ar.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [32]:
# Get a specific element [r,c]

a[1,5]
a[1,-2]

13

In [33]:
# Get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
#Get a specific column

a[:,2]

array([ 3, 10])

In [36]:
# Getting little advanced [startindex:endindex:stepsize]

a[0,1:6:2]

a[0,1:-1:2]


array([2, 4, 6])

In [38]:
a[1,5] = 15
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]


In [39]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 15 14]]


In [42]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 15 14]]


In [44]:
# 3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
# Get specific element

b[0,1,1]

b[:,1,:]


array([[3, 4],
       [7, 8]])

In [48]:
# replace

b[:,1,:] = [[9,9],[8,8]]

print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [52]:
# all o's matrix

#np.zeros()
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [53]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [55]:

np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [56]:
#full_like

np.full_like(a, 4 )

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
#Randoom decimal numbers

np.random.rand(4,2,3)

array([[[0.21283403, 0.85716992, 0.16542433],
        [0.4064132 , 0.26674207, 0.83457058]],

       [[0.50619265, 0.86628675, 0.79612723],
        [0.2835008 , 0.22350944, 0.61037309]],

       [[0.52902613, 0.0247036 , 0.36724591],
        [0.30739786, 0.6210646 , 0.53732634]],

       [[0.48296078, 0.66746906, 0.71061558],
        [0.3637872 , 0.66365686, 0.17754263]]])

In [60]:
#np.random.rand_sample(a.shape)
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 15, 14]])

In [64]:
# Random Integer values

np.random.randint(4,6, size=(3,3))

array([[4, 5, 4],
       [4, 5, 4],
       [5, 4, 4]])

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 1)

r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
r1.size
r1.shape
r1.ndim

2

In [84]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1] = 9

print(z)

output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [90]:
x = np.array([1,2,3])
y =x
print(x)
print(y)

y[0] = 15
print(y)
print(x)


[1 2 3]
[1 2 3]
[15  2  3]
[15  2  3]


In [89]:
y = x.copy()
y[0] = 15
print(y)
print(x)

[15  2  3]
[1 2 3]


In [91]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [92]:
a+= 2
a-2
a*2
a/2
a**2

array([3, 4, 5, 6])

In [93]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [94]:
# take sign

np.sin(a)

np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [99]:
# Linear algebra

a= np.ones((2,3))
print(a)

b= np.full((3,2), 2)

print(b)
  
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [100]:
c= np.identity(3)

np.linalg.det(c)

1.0

In [102]:
#Statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.min(stats, axis =1)

array([1, 4])

In [105]:
np.max(stats)

6

In [106]:
np.sum(stats)

21

In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [109]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [111]:
#Verically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [117]:
# horizontal stack

h1= np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [124]:
filedata = np.genfromtxt('data.txt', delimiter=',')

filedata = filedata.astype('int32')

filedata


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [126]:
# Advanced indexing boolean masking

filedata > 50

filedata[filedata  > 50]



array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [127]:
# you can index with a list with NUmPy

a= np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]



array([2, 3, 9])

In [128]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [129]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [130]:
# axis = 1 Rows

np.all(filedata > 50, axis = 1)

array([False, False, False])

In [132]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])